apiVersion: v2
name: cray-metallb
version: 1.1.0
description: MetalLB is a load-balancer implementation for bare metal Kubernetes clusters
home: https://github.com/Cray-HPE/cray-metallb
dependencies:
  - name: metallb
    version: 0.11.0
    repository: https://metallb.github.io/metallb
maintainers:
  - name: johren-hpe
  - name: bklei
appVersion: v0.11.0  # Tracks metallb image tags
annotations:
  artifacthub.io/images: |-
    - name: kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.15
    - name: metallb-controller
      image: artifactory.algol60.net/csm-docker/stable/quay.io/metallb/controller:v0.11.0
    - name: metallb-speaker
      image: artifactory.algol60.net/csm-docker/stable/quay.io/metallb/speaker:v0.11.0
  artifacthub.io/license: MIT
