#
# Until https://github.com/metallb/metallb/issues/995 is resolved, we'll patch
# to add pod priority class name to speaker and controller pods.  Once we pull
# in a version of metallb that contains this fix, at which time we can remove
# the patch-pod-priority.yaml file in the templates directory, as well
# as this kubectl image:
#
kubectl:
  repository: artifactory.algol60.net/csm-docker/stable/docker-kubectl
  tag: 1.19.15

metallb:
  nameOverride: "metallb"
  fullnameOverride: metallb
  configInline: {}
  #
  # Config map will get created with customizations per environment as follows:
  #
  # configInline:
  #   peers:
  #   - peer-address: 10.252.0.2
  #     peer-asn: 65533
  #     my-asn: 65533
  #   address-pools:
  #   - name: customer-access
  #     protocol: bgp
  #     addresses:
  #     - 10.101.10.128/25
  #
  prometheus:
    scrapeAnnotations: true
    prometheusRule:
      enabled: true
    podMonitor:
      enabled: true
  controller:
    image:
      registry: quay.io
      repository: metallb/controller
      tag: v0.11.0
    resources:
      requests:
        cpu: "2"
        memory: 2Gi
      limits:
        cpu: "8"
        memory: 16Gi
    serviceAccount:
      create: true
      name: "controller"
  speaker:
    image:
      registry: quay.io
      repository: metallb/speaker
      tag: v0.11.0
    resources:
      requests:
        cpu: "2"
        memory: 2Gi
      limits:
        cpu: "8"
        memory: 16Gi
    serviceAccount:
      create: true
      name: "speaker"
