apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metallb.fullname" . }}-hook-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
    app.kubernetes.io/component: hook-pvc
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5" 
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
