apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metallb.fullname" . }}-crd-generator-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
    app.kubernetes.io/component: crd-generator-script
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  generate_metallb_crds.py: |-
{{ .Files.Get "files/generate_metallb_crds.py" | indent 4 }}