apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metallb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "metallb.fullname" . }}-secret-reader
  namespace: loftsman
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["site-init"]
  verbs: ["get"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "metallb.fullname" . }}-bind-secret-reader
  namespace: loftsman
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "metallb.fullname" . }}-secret-reader
subjects:
- kind: ServiceAccount
  name: {{ include "metallb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }} 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "metallb.fullname" . }}-hook-operations
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
rules:
# Permissions for Hook 1 to manage the generated CRD ConfigMap
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch", "delete"]
# Permissions for Hook 2 to read the generated CRD ConfigMap
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["{{ .Release.Name }}-metallb-generated-crds"] # Restricted name
  verbs: ["get"]
# Permissions for Hook 2 to apply MetalLB CRDs
- apiGroups: ["metallb.io"]
  resources: ["ipaddresspools", "bgppeers", "bgpadvertisements"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "metallb.fullname" . }}-bind-hook-operations
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "metallb.fullname" . }}-hook-operations 
subjects:
- kind: ServiceAccount
  name: {{ include "metallb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  