apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metallb.fullname" . }}-crd-generator-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
    app.kubernetes.io/component: crd-generator-script
data:
  generate_metallb_crds.py: |-
{{ .Files.Get "files/generate_metallb_crds.py" | indent 4 }}
